FROM mysql:8.0

EXPOSE 3306

COPY init.sql docker-entrypoint-initdb.d/init.sql

CMD ["mysqld", "--server-id=2", "--bind-address=0.0.0.0", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--log_bin=/var/log/mysql/mysql-bin.log", "--expire_logs_days=90"]
