version: '3.7'

services:
  localstack:
    build: .
    container_name: localstack
    environment:
      - SERVICES=sqs
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
    ports:
      - 45661:4566
    volumes:
      - ./.data:/tmp/localstack/data
