version: '3.8'

services:
  mongo:
    container_name: mongo
    build:
      context: .
      dockerfile: dockerfile
    environment:
      TZ: Asia/Seoul
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./data:/var/lib/mongodb
      - ./logs:/var/log/mongodb
    ports:
      - 27018:27017
    restart: always
