FROM node:20

EXPOSE 3000

WORKDIR /var/app

COPY .env.docker .env
COPY package-lock.json package-lock.json
COPY package.json package.json 
COPY dist dist

RUN npm ci --omit=dev

CMD ["node", "dist/main.js"]
