version: '3.8'

name: local

services:
  localstack:
    container_name: localstack
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DATA_DIR: /tmp/localstack/data
      AWS_DEFAULT_REGION: ap-northeast-2
      SERVICES: sqs
      DEBUG: 1
    volumes:
      - ./tmp:/tmp
    ports:
      - 4566:4566
    restart: always
    networks:
      - localhost

networks:
  localhost:
    name: localhost
    driver: bridge
